server:
  port: 8083
  servlet:
    context-path: /blog
spring:
  rabbitmq:
    host: localhost
    virtual-host: /email
    port: 5672
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    username: 2927697242@qq.com
    password: nltlcygbednxdgea
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        cluster-name: ShangHai #配置集群
#        namespace: 4981c7e3-e3c9-481d-8ec0-16611aba0394 #命名空间的id

  # 标记应用名称,用于nacos注册
  application:
    name: blogTypeService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    host: 8.140.17.235
  #    host: 192.168.80.128
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 350MB
mybatis-plus:
  type-aliases-package: com.ntx.blogType.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.ntx: debug
ribbon:
  eager-load:
    enabled: true


#eureka:
#  client:
#    service-url:
#      defaultZone: http:127.0.0.1:10086/eureka