server:
  port: 10086
spring:
  application:
    name: eurekaServer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/euraka
    register-with-eureka: false # 表示不向注册中心注册
    fetch-registry: false # 由于注册中心的职责就是维护服务实例，所以它不需要去检索服务

